name: ModuleB
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    #actions/checkout@main
      - uses: actions/checkout@v3
      
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      #- name: Create Azure and Vnets and VM
        #uses: Azure/cli@v1.0.6
        #with:
          # Azure CLI version to be used to execute the script. If not provided, latest version is used
          # azcliversion: 2.34.1 # optional, default is agentazcliversion
          # Specify the script here
          #inlineScript: |
           # az deployment sub create --name rgdeploy --location northeurope --template-file main.bicep
            
      - name: Create kubernetes and mesh
        uses: Azure/cli@v1.0.6
        with:
          # Azure CLI version to be used to execute the script. If not provided, latest version is used
          # azcliversion: 2.34.1 # optional, default is agentazcliversion
          # Specify the script her
          inlineScript: |
            az deployment group create \
            --name OSMBicepDeployment \
            --resource-group rg-spoke-001\
            --template-file aks.bicep \
            --parameters aksparameters.json
